{% set name = "opentelemetry-instrumentation-system-metrics" %}
{% set version = "0.53b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_system_metrics-{{ version }}.tar.gz
  sha256: fbcc15900f5e8a0c99d85ee6cb9529ecfcbfbe9e6b6d6e158ac80340f40df779

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-instrumentation ==0.53b0
    - opentelemetry-api >=1.11,<2.dev0
    - opentelemetry-sdk >=1.25,<2.0
    - psutil >=5.9.0,<8

test:
  imports:
    - opentelemetry.metrics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-system-metrics.
  summary: OpenTelemetry System Metrics Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-instrumentation
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-sdk
