{% set name = "opentelemetry-instrumentation-system-metrics" %}
{% set version = "0.45b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_system_metrics-{{ version }}.tar.gz
  sha256: 776ec5dd71d7de9bd499d2b561424a2be323a36b32c07c3d3983fcf4e03215e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - opentelemetry-instrumentation ==0.45b0
    - python >=3.7
    - opentelemetry-api >=1.11,<2.dev0
    - opentelemetry-sdk >=1.11,<2.dev0
    - psutil >=5.9,<6.dev0

test:
  imports:
    - opentelemetry.metrics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-system-metrics.
  summary: OpenTelemetry System Metrics Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
