{% set name = "opentelemetry-instrumentation-system-metrics" %}
{% set version = "0.52b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_system_metrics-{{ version }}.tar.gz
  sha256: 8e9fdea1ebffb50ecb2907e4fc7c92605d63bd46fe9a6ed731a22f9334e27a16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-instrumentation ==0.52b1
    - opentelemetry-api ~=1.11
    - opentelemetry-sdk >=1.25,<2.0
    - psutil >=5

test:
  imports:
    - opentelemetry.metrics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-system-metrics.
  summary: OpenTelemetry System Metrics Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-instrumentation
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-sdk
